# Site settings
title: Christoph von Krüchtens Blog
email: christoph@vonkruechten.de
description: > # this means to ignore newlines until "baseurl:"
    Dies ist mein Blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.vonkruechten.de" # the base hostname & protocol for your site
twitter_username: cvk77
github_username:  cvk77

# Build settings
markdown: kramdown
